// packages/Triton.Vue/src/components/Plates/Spotify.vue
<template>
  <VPlate brandIcon="spotify" brandTitle="Spotify" brandClass="spotify-plate" brandColor="#B5EB00">
    <VLabel v-bind:title="$t('Username')" v-bind:value="Username"/>
    <VLabel v-bind:title="$t('Email')" v-bind:value="Email" noCapitalize="true"/>
    <VLabel v-bind:title="$t('Type')" v-bind:value="Type" isLast="true" addClass="color"/>
  </VPlate>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import VPlate from "@/components/Utils/VPlate.vue";
import VLabel from "@/components/Utils/VLabel.vue";

@Component({
  components: {
    VPlate,
    VLabel
  }
})
export default class Spotify extends Vue {
  protected Username: string = this.$store.state.Spotify.Username;
  protected Type: string = this.$store.state.Spotify.Type;
  protected Email: string = this.$store.state.Spotify.Email;
}
</script>

<style lang="scss">
@import "../../assets/scss/index.scss";

.spotify-plate {
  display: flex;
  justify-content: space-between;

  .details {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
  }

  .color {
    color: $spotify;
  }
}
</style>

<i18n>
  {
  "en": {
  "Username": "User name",
  "Email": "Email",
  "Type" :"Account type"
  },
  "pl": {
  "Username": "Użytkownik",
  "Email": "Email",
  "Type" :"Typ konta"
  }
  }
</i18n>

// packages/triton.react/src/components/Plates/Spotify.tsx
import React, { Component } from "react";
import { WithNamespaces, withNamespaces } from "react-i18next";
import VLabel from "../Utils/VLabel";
import Plate from "./Plate";
import "./Spotify.scss";

class Spotify extends Component<WithNamespaces> {
  public state = {
    username: "test",
    email: "test",
    type: "test"
  };

  render() {
    const { t } = this.props;
    return (
      <Plate
        plateBrand="Spotify"
        plateClass="spotify-plate"
        plateBrandColor="#B5EB00"
      >
        <aside className="details">
          <VLabel title={t("Spotify.username")} value={this.state.username} />
          <VLabel
            title={t("Spotify.email")}
            value={this.state.email}
            noCapitalize={true}
          />
          <VLabel
            title={t("Spotify.type")}
            value={this.state.type}
            isLast={true}
            addClass="color"
          />
        </aside>
      </Plate>
    );
  }
}

export default withNamespaces("services")(Spotify);
