// packages/triton.react/src/components/Plates/DigitalOcean.tsx
import React, { Component } from "react";
import { WithNamespaces, withNamespaces } from "react-i18next";
import VLabel from "../Utils/VLabel";
import "./DigitalOcean.scss";
import Plate from "./Plate";

class DigitalOcean extends Component<WithNamespaces> {
  public state = {
    email: "",
    lastCreatedDroplet: "",
    dropletlimit: "",
    total: ""
  };

  render() {
    const { t } = this.props;
    const { email, lastCreatedDroplet, dropletlimit, total } = this.state;
    return (
      <Plate
        plateBrand="DigitalOcean"
        plateClass="digital-ocean-plate"
        plateBrandColor="#0080FF"
      >
        <div className="details">
          <aside className="wrap">
            <VLabel
              title={t("DigitalOcean.email")}
              value={email}
              noCapitalize={true}
            />
            <VLabel
              title={t("DigitalOcean.lastCreatedDroplet")}
              value={
                lastCreatedDroplet +
                " " +
                (lastCreatedDroplet.length > 0
                  ? t("DigitalOcean.hoursAgo")
                  : "")
              }
              isLast={true}
              addClass="color"
            />
          </aside>

          <aside className="wrap">
            <VLabel
              title={t("DigitalOcean.dropletLimit")}
              value={dropletlimit}
              addClass="color"
            />
            <VLabel
              title={t("DigitalOcean.droplets")}
              value={total}
              isLast={true}
              addClass="color"
            />
          </aside>
        </div>
      </Plate>
    );
  }
}

export default withNamespaces("services")(DigitalOcean);

// packages/Triton.Vue/src/components/Plates/DigitalOcean.vue
<template>
  <VPlate brandIcon="digital-ocean" brandTitle="DigitalOcean" brandClass="digital-ocean-plate" brandColor="#0080FF">
    <aside class="wrap">
      <VLabel v-bind:title="$t('Email')" v-bind:value="Email"/>
      <VLabel v-bind:title="$t('LastCreatedDroplet')" v-bind:value="LastCreatedDroplet + ' ' + $t('LastCreatedDroplet')"
              isLast="true" addClass="color"/>
    </aside>
    <aside class="wrap">
      <VLabel v-bind:title="$t('DropletLimit')" v-bind:value="DropletLimit" addClass="color"/>
      <VLabel v-bind:title="$t('Droplets')" v-bind:value="Droplets" isLast="true" addClass="color"/>
    </aside>
  </VPlate>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import VPlate from "@/components/Utils/VPlate.vue";
import VLabel from "@/components/Utils/VLabel.vue";

@Component({
  components: {
    VPlate,
    VLabel
  }
})
export default class DigitalOcean extends Vue {
  protected Email: string = this.$store.state.DigitalOcean.Email;
  protected LastCreatedDroplet: string = this.$store.state.DigitalOcean
    .LastCreatedDroplet;
  protected DropletLimit: string = this.$store.state.DigitalOcean.DropletLimit;
  protected Droplets: string = this.$store.state.DigitalOcean.Total;
}
</script>

<style lang="scss">
@import "../../assets/scss/index.scss";

.digital-ocean-plate {
  .details {
    display: flex;
    justify-content: space-between;
    flex-wrap: wrap;

    @include queries("mobileMax") {
      .wrap:nth-child(2) {
        margin-left: 20px;
      }
    }
  }

  .color {
    color: $digital_ocean;
  }
}
</style>

<i18n>
  {
  "en": {
  "Email": "Email",
  "LastCreatedDroplet": "Last created droplet",
  "DropletLimit" :"Droplet limit",
  "Droplets" :"Droplets"
  },
  "pl": {
  "Email": "Email",
  "LastCreatedDroplet": "Ostatnio utworzony droplet",
  "DropletLimit" :"Limit dropletów",
  "Droplets" :"Dropletów"
  }
  }
</i18n>
